version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/code/api
    command: >
      sh -c 'uvicorn api.main:app --host 0.0.0.0 --port 5000'

  tasks:
    container_name: tasks
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./api:/code/api
    command: >
      sh -c 'celery -A api.tasks.celery worker --loglevel=info'

  mkdocs:
    container_name: mkdocs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    working_dir: /
    volumes:
      - ./docs:/docs
      - ./mkdocs.yml:/mkdocs.yml
    command: mkdocs serve --dev-addr=0.0.0.0:5002 --livereload

  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - api
    volumes:
      - ./webapp:/code/webapp
    command: >
      streamlit run webapp/app.py --server.port 5001

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pg_data: {}
  pg_backups: {}