site_name: Data Theorem Assessment 
repo_url: https://github.com/denisvolokh/data-theorem-assessment
site_author: Denis Volokh

nav:
  - Assessment: assessment.md
  - Setup: setup.md
  - Solution: solution.md
  - API Docs: swagger.md

plugins:
  - render_swagger:
      allow_arbitrary_locations : true